import { getSession, useSession } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import Brands from '../components/Brands'
import Header from '../components/Header'
import LandingPage from '../components/LandingPage'
import Slider from '../components/Slider'


export default function Home() {
  const {data:session} = useSession();
  return (
    <div className="">
      <Head>
        <title>Disney+ | Watch TV Shows, Movies, Specials, Live Sports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {
        !session ? (<LandingPage/>) :
        (
          <main>
            <Slider className="" />
            <Brands />
          </main>
        )

        
      }
      

      
    </div>
  )
}

export async function getServerSideProps(context) {

  const session = await getSession(context);
  return {
    props: {
      session,
    },
  }
}