import { getSession, useSession } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import Brands from '../components/Brands'
import Header from '../components/Header'
import LandingPage from '../components/LandingPage'
import MovieCollection from '../components/MovieCollection'
import Banner from '../components/Banner'


export default function Home({movieList}) {
  const {data:session} = useSession();
  return (
    <div className="">
      <Head>
        <title>Disney+ | Watch TV Shows, Movies, Specials, Live Sports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {
        !session ? (<LandingPage/>) :
        (
          <main className="relative min-h-screen after:bg-home after:bg-center after:bg-cover after:bg-no-repeat after:bg-fixed after:absolute after:inset-0 after:z-[-1]">
            <Banner className="" />
            <Brands />
            <MovieCollection category="recommend" movlist={movieList} />
            <MovieCollection category="new" movlist={movieList} />
            <MovieCollection category="original" movlist={movieList} />
            <MovieCollection category="trending" movlist={movieList} />
          </main>
        )

        
      }
      

      
    </div>
  )
}

export async function getServerSideProps(context) {
  let url = process.env.HOST + '/api/movies'
  const movieList = await(await fetch(url)).json()
  return {
    props: {
      movieList,
    },
  }
}